export { Header } from "./Header";
export { Footer } from "./Footer";
export { StepsBlock } from "./StepsBlock";
export { NewsBlock } from "./NewsBlock";
export { ResultsBlock } from "./ResultsBlock";
export { PartnersBlock } from "./PartnersBlock";
export { PaginationBlock } from "./PaginationBlock";
export { AwardsBlock } from "./AwardsBlock";
export { GalleryBlock } from "./GalleryBlock";